### ISSUE TITLE
[BACK] Alterar endpoint `/professores/todos` para retornar uma lista de objetos com apenas o nome e id do professor

### ISSUE THREAD

**Issue by tauanesales** [tauanesales/Sistema-PGCop-UFBA#101]
# Descrição

Atualmente o endpoint `/professores/todos` retorna todas as informações do orientador, quando apenas é utilizado o nome e id. Idealmente deve-se retornar apenas o que será utilizado.

# TODO
- [x] Alterar endpoint `/professores/todos` para retornar uma lista de objetos com apenas o nome e id do professor.

## Response atual
```json
[
  {
    "nome": "Sem Orientador",
    "email": "sem_orientador@ufba.br",
    "tipo_usuario": "PROFESSOR",
    "id": 1,
    "usuario_id": 15
  },
  {
    "nome": "Coord Fred Durão",
    "email": "fred_coordenador@ufba.br",
    "tipo_usuario": "COORDENADOR",
    "id": 2,
    "usuario_id": 3
  },
  {
    "nome": "rafael coord",
    "email": "rafa_coordenador@example.com",
    "tipo_usuario": "COORDENADOR",
    "id": 3,
    "usuario_id": 11
  },
  {
    "nome": "rafael prof",
    "email": "rafa_professor@example.com",
    "tipo_usuario": "PROFESSOR",
    "id": 4,
    "usuario_id": 12
  },
  {
    "nome": "Sem Orientador",
    "email": "sem_orientador@uba.br",
    "tipo_usuario": "PROFESSOR",
    "id": 5,
    "usuario_id": 13
  },
  {
    "nome": "Sem Orientador",
    "email": "sem_orientador@ubfa.br",
    "tipo_usuario": "PROFESSOR",
    "id": 6,
    "usuario_id": 14
  },
  {
    "nome": "Prof Fred Durão",
    "email": "fred_professor@ufba.br",
    "tipo_usuario": "PROFESSOR",
    "id": 7,
    "usuario_id": 1
  }
]
```

## Response desejado
```json
[
  {
    "nome": "Sem Orientador",
    "id": 1
  },
  {
    "nome": "Coord Fred Durão",
    "id": 2
  },
  {
    "nome": "rafael coord",
    "id": 3,
  },
  {
    "nome": "rafael prof",
    "id": 4
  },
  {
    "nome": "Sem Orientador",
    "id": 5
  },
  {
    "nome": "Sem Orientador",
    "id": 6
  },
  {
    "nome": "Prof Fred Durão",
    "id": 7
  }
]
```

# Critério de aceite do PR
No PR, deve ser submetido um print batendo no endpoint localmente e ele respondendo dentro do esperado.
Escrever "FIXES #101" na descrição do PR.

**Comment by alexgondim** [comment]
Tauane eu entendo que devemos ai criar um endpoint /professores/todos que vai retornar apenas os campos nome e id para cada professor. Os dados são filtrados utilizando uma list comprehension para gerar a lista de dicionários simplificados. Veja no exemplo se é isso que vc esta precisando? 

professores = [
    {
        "nome": "Sem Orientador",
        "email": "sem_orientador@ufba.br",
        "tipo_usuario": "PROFESSOR",
        "id": 1,
        "usuario_id": 15
    },
    {
        "nome": "Coord Fred Durão",
        "email": "fred_coordenador@ufba.br",
        "tipo_usuario": "COORDENADOR",
        "id": 2,
        "usuario_id": 3
    },
    {
        "nome": "rafael coord",
        "email": "rafa_coordenador@example.com",
        "tipo_usuario": "COORDENADOR",
        "id": 3,
        "usuario_id": 11
    },
    {
        "nome": "rafael prof",
        "email": "rafa_professor@example.com",
        "tipo_usuario": "PROFESSOR",
        "id": 4,
        "usuario_id": 12
    },
    {
        "nome": "Sem Orientador",
        "email": "sem_orientador@uba.br",
        "tipo_usuario": "PROFESSOR",
        "id": 5,
        "usuario_id": 13
    },
    {
        "nome": "Sem Orientador",
        "email": "sem_orientador@ubfa.br",
        "tipo_usuario": "PROFESSOR",
        "id": 6,
        "usuario_id": 14
    },
    {
        "nome": "Prof Fred Durão",
        "email": "fred_professor@ufba.br",
        "tipo_usuario": "PROFESSOR",
        "id": 7,
        "usuario_id": 1
    }
]

@app.get("/professores/todos")
async def get_professores():
    # Filtra os dados para incluir apenas o nome  e o  id
    professores_simplificados = [{"nome": prof["nome"], "id": prof["id"]} for prof in professores]
    return professores_simplificados
