### ISSUE TITLE
[BACK] Solicitações para orientador "SEM_ORIENTADOR" (id 1) devem ser ignoradas

### ISSUE THREAD

**Issue by tauanesales** [tauanesales/Sistema-PGCop-UFBA#126]
# Descrição

Atualmente é possível abrir solicitação de orientação para orientador ID 1 (Sem Orientador). Como isso não faz sentido, se o ID for 1 a função deve apenas parar o fluxo.

**Comment by marioaugustosantos** [comment]
Seguem as evidências:

![02](https://github.com/user-attachments/assets/99050a69-7f10-4722-949c-905834b0c5c2)
![01](https://github.com/user-attachments/assets/e883a654-f46d-4faa-b09d-ccc0af5b94e0)
