### ISSUE TITLE
[BACK] Retornar tarefa ao atualizar

### ISSUE THREAD

**Issue by RafaelCostaF** [tauanesales/Sistema-PGCop-UFBA#140]
No endpoint:
PUT /tarefas/{tarefa_id}

Hoje é retornado apenas o status 204, e uma string com conteúdo "string". 
![image](https://github.com/user-attachments/assets/6d2e970a-c8bd-423b-9f4f-60ddf3a52cda)

Retornar a tarefa em formato json, conforme exemplo abaixo: 
![image](https://github.com/user-attachments/assets/fc802ef1-f34e-4bf0-ab3b-6e88ed268739)

**Comment by bacelarjunior** [comment]
Response de tarefa corrigido no endpoint PUT /tarefas/{tarefa_id}
![image](https://github.com/user-attachments/assets/5a7c153d-c094-4202-ae10-362acf2f06ce)
