### ISSUE TITLE
[BACK] Autenticar rota de busca de professores por id `/professores/{professor_id}`

### ISSUE THREAD

**Issue by tauanesales** [tauanesales/Sistema-PGCop-UFBA#80]
- GET `/professores/{professor_id}` deve ser autenticado (receber token);
- Apenas professores e coordenadores devem ser capazes de buscar informação de professores por ID.

# Critério de aceite do PR
No PR, deve ser submetido um print batendo no endpoint localmente e ele respondendo dentro do esperado.
Escrever "FIXES #80" na descrição do PR.

**Comment by alexgondim** [comment]
Explicação das Modificações
Dependência de Segurança:

oauth2_scheme foi definido no início do arquivo para extrair o token.
Função de Verificação do Token:

get_current_user é a função que decodifica o token JWT e retorna os dados do usuário autenticado.
Aplicação da Dependência no Endpoint:

No endpoint buscar_professor_por_id, adicionamos current_user: TokenData = Depends(get_current_user) para garantir que ele só seja acessível por usuários autenticados.
