### ISSUE TITLE
[BACK] Autenticar rota de busca de tarefas por aluno/curso

### ISSUE THREAD

**Issue by tauanesales** [tauanesales/Sistema-PGCop-UFBA#91]
- GET `/tarefas/aluno/{aluno_id}` deve ser autenticado (receber token);
- GET `/tarefas_base/curso/{curso}` deve ser autenticado (receber token);
- Apenas **professores e coordenadores** devem ser capazes de buscar tarefas por id de aluno ou curso.

# Critério de aceite do PR
No PR, deve ser submetido um print batendo no endpoint localmente e ele respondendo dentro do esperado.
Escrever "FIXES #91" na descrição do PR.

**Comment by marioaugustosantos** [comment]
Seguem Evidencias

![4 - Tarefas Base - Aluno - Evidência - Autenticado](https://github.com/user-attachments/assets/5175ca49-b225-4556-ad84-698dcc583c7c)
![3 - Tarefas Base - Aluno - Evidência - Não Autenticado](https://github.com/user-attachments/assets/d08fc36d-93c6-4292-ab1d-7ce65d8c4ee8)
![2 - Tarefas Base - Curso - Evidência - Autenticado](https://github.com/user-attachments/assets/15d47778-d798-4351-93ac-a6a46f469b2a)
![1 - Tarefas Base - Curso - Evidência - Não Autenticado](https://github.com/user-attachments/assets/f0a89ca4-7e77-4ca8-b57c-4989f462f53a)
